# Generated by Django 5.0.7 on 2024-07-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GasMeterData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dev_eui", models.CharField(max_length=16, verbose_name="Device EUI")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "accumulated_flow",
                    models.IntegerField(verbose_name="Accumulated Flow (L)"),
                ),
                ("total_flow", models.IntegerField(verbose_name="Total Flow (L)")),
                ("meter_status", models.IntegerField(verbose_name="Meter Status")),
                ("alarm", models.IntegerField(verbose_name="Alarm")),
                (
                    "battery_voltage",
                    models.FloatField(verbose_name="Battery Voltage (V)"),
                ),
                ("rssi", models.IntegerField(verbose_name="RSSI")),
                ("snr", models.IntegerField(verbose_name="SNR")),
            ],
            options={
                "verbose_name": "Gas Meter Data",
                "verbose_name_plural": "Gas Meter Data",
                "ordering": ["-timestamp"],
            },
        ),
    ]
